site_name: AutoAgora Agents

nav:
  - Home : index.md
  - Python API : api.md
  - Simulation : sim.md

theme: material 

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_root_heading: true
          heading_level: 3
          filters: ["!_"]

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format