name: Build Documents

on:
  push:
    branches:
      - master

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      # https://github.com/actions/runner-images/issues/6185
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

    permissions:
      contents: write

    steps:    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.2.2'

      - name: Install dependencies
        run: poetry install --only docs
      
      - name: Get Version
        id: version
        run: echo "latest=v$(poetry run semantic-release print-version --current)" >> $GITHUB_OUTPUT
      
      - name: Print version
        run: echo "Latest documents version ${{ steps.version.outputs.latest }}."

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - run: poetry run mike deploy --push --rebase --update-aliases ${{ steps.version.outputs.latest }} latest
      - run: poetry run mike set-default latest
